/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as OwenRouteImport } from './routes/owen'
import { Route as IndexRouteImport } from './routes/index'

const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const OwenRoute = OwenRouteImport.update({
  id: '/owen',
  path: '/owen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owen': typeof OwenRoute
  '/quick-start': typeof QuickStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owen': typeof OwenRoute
  '/quick-start': typeof QuickStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owen': typeof OwenRoute
  '/quick-start': typeof QuickStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/owen' | '/quick-start'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/owen' | '/quick-start'
  id: '__root__' | '/' | '/owen' | '/quick-start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwenRoute: typeof OwenRoute
  QuickStartRoute: typeof QuickStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owen': {
      id: '/owen'
      path: '/owen'
      fullPath: '/owen'
      preLoaderRoute: typeof OwenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwenRoute: OwenRoute,
  QuickStartRoute: QuickStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
