/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as OwenRouteImport } from './routes/owen'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideSafetyRouteImport } from './routes/guide.safety'

const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const OwenRoute = OwenRouteImport.update({
  id: '/owen',
  path: '/owen',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSafetyRoute = GuideSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => GuideRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/owen': typeof OwenRoute
  '/quick-start': typeof QuickStartRoute
  '/guide/safety': typeof GuideSafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/owen': typeof OwenRoute
  '/quick-start': typeof QuickStartRoute
  '/guide/safety': typeof GuideSafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/owen': typeof OwenRoute
  '/quick-start': typeof QuickStartRoute
  '/guide/safety': typeof GuideSafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guide' | '/owen' | '/quick-start' | '/guide/safety'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide' | '/owen' | '/quick-start' | '/guide/safety'
  id: '__root__' | '/' | '/guide' | '/owen' | '/quick-start' | '/guide/safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRouteWithChildren
  OwenRoute: typeof OwenRoute
  QuickStartRoute: typeof QuickStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owen': {
      id: '/owen'
      path: '/owen'
      fullPath: '/owen'
      preLoaderRoute: typeof OwenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/safety': {
      id: '/guide/safety'
      path: '/safety'
      fullPath: '/guide/safety'
      preLoaderRoute: typeof GuideSafetyRouteImport
      parentRoute: typeof GuideRoute
    }
  }
}

interface GuideRouteChildren {
  GuideSafetyRoute: typeof GuideSafetyRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideSafetyRoute: GuideSafetyRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRouteWithChildren,
  OwenRoute: OwenRoute,
  QuickStartRoute: QuickStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
